### ISSUE TITLE
Reduce Docker building time of binder tutorials

### ISSUE THREAD

**Issue by yoavnash** [simphony/docs#138]
Currently, every time we fire up a binder tutorial, the image has to be built.
Instead, we can upload Docker images to Docker Hub to save that time.

Links:
- https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html#when-you-must-inherit-from-a-popular-docker-image
- https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956

**Comment by pablo-de-andres** [comment]
It looks like this might not be an issue any more. During the development, we were using the dev branch, which was changing often. 
Since now they are built from master, and it does not change, the stored images can be used:
Example:
https://mybinder.org/v2/gh/simphony/docs/master?filepath=docs%2Fsource%2Fjupyter%2Fcuds_api.ipynb
