### ISSUE TITLE
Document all methods and properties of OntologyEntity and its subclasses

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/docs#65]
The tutorials should probably be updated to include these as well

**Comment by pablo-de-andres** [comment]
### For iris
- `class.iri` or `instance.iri`
- Util functions to convert from uid to iri

**Comment by kysrpex** [comment]
I am working on this and would like to leave a comment.

I do not think that we should actually document all methods and properties in a tutorial, but just the most useful. Otherwise we would have an API reference instead of a tutorial. I am doing it in this way. For example: it's pointless to include the public method `get` of `OntologyNamespace`, as it provides no advatange to the user over easier methods of accessing the entities in the namespace. A similar thing happens with the `tblname` property of `OntologyEntity`. It does not provide useful information to the user.

Nevertheless, the API reference should be expanded to include the classes for the different ontology entitites and the namespace object, so that the users can have the full information if they want it. I will create an issue for this.
