### ISSUE TITLE
Make tutorials interactive with binder

### ISSUE THREAD

**Issue by kysrpex** [simphony/docs#80]
Binder allows the user to open a certain file in a Jupyter notebook to immediately experiment with it with zero configuration and installation steps. It would be a good idea to give user's access to the examples in this way.

**Comment by pablo-de-andres** [comment]
Looks like readthedocs has no native integration with binder (see [issue](https://github.com/sphinx-gallery/sphinx-gallery/issues/503)).

**Comment by kysrpex** [comment]
Then we could just offer a button at the beginning of the tutorial to open it with binder 😢.

**Comment by pablo-de-andres** [comment]
Yes, I was just thinking about that. We could add a badge with the link to Binder.
I just tried to run one of the tutorials out of the box, but binder fails when automatically installing the docs repo.
We might have to look into that

**Comment by pablo-de-andres** [comment]
__Note:__ Probably has to do with the custom install script that automatically builds the docs when installing

**Comment by pablo-de-andres** [comment]
**Note:** According to [the binder documentation](https://mybinder.readthedocs.io/en/latest/using/config_files.html#dockerfile-advanced-environments), binder will build based on a Dockerfile when one is present. However, the Dockerfile we use is meant to start a server for rendering the docs locally. The options I can think of:
- Rename the Dockerfile to something like "build_locally.Dockerfile", and provide the name in the build command via `-f`. It must be checked that binder won't pick up one with a different name.
- Remove the `CMD` line in the Dockerfile that starts the server and just print the command so that the user can run it when running the image interactively.

**Comment by kysrpex** [comment]
- Detect in the dockerfile if it is running in Binder.

**Comment by pablo-de-andres** [comment]
@yoavnash @kysrpex 
An issue here. The binder badge will have a link pointing to the file in GitHub, which means it has to include (hardcoded) the branch name. Since it should probably be master, it also means it won't be fully testable until we merge to master at the end of the sprint.

**Comment by kysrpex** [comment]
> @yoavnash @kysrpex
> An issue here. The binder badge will have a link pointing to the file in GitHub, which means it has to include (hardcoded) the branch name. Since it should probably be master, it also means it won't be fully testable until we merge to master at the end of the sprint.

I guess we can still click and then change the address, so it would be almost tested. We may be lucky if there is some trick Sphinx can do for us here.
